# Generated by Django 5.1.6 on 2025-03-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userpreferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
